version: 2.1
orbs:
  node: circleci/node@5.0.2

# install packages
jobs:
  build:
    docker:
      - image: circleci/node:latest
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn install
workflows:
  build:
    jobs:
      - build
