version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  format:
    docker:
      - image: cimg/node:lts
        environment:
          DATA_BASE_URL: DATA_BASE_URL
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn format
  lint:
    docker:
      - image: cimg/node:lts
        environment:
          DATA_BASE_URL: DATA_BASE_URL
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
  test:
    docker:
      - image: cimg/node:lts
        environment:
          DATA_BASE_URL: DATA_BASE_URL
    steps:
      - checkout
  build:
    docker:
      - image: cimg/node:lts
        environment:
          DATA_BASE_URL: DATA_BASE_URL
        
    steps:
      - checkout

workflows:
  format:
    jobs:
      - build
  test:
    jobs:
      - test
  build:
    jobs:
      - build
  lint:
    jobs:
      - build