version: 2.1
orbs:
  node: circleci/node@5.0.2

# install packages
jobs:
  build:
    docker:
      - image: cimg/node:16.20.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: echo "Building Planet of the Bugs"
  test:
    docker:
      - image: cimg/node:16.20.1
    steps:
      - checkout
      - run: echo "this is the build job"
  deploy:
    docker:
      - image: cimg/node:16.20.1
    steps:
      - checkout
      - run: echo "this is the build job"
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy