version: 2.1
orbs:
  node: circleci/node@5.0.2
  1password: onepassword/secrets@1.0.0

jobs:
  preview_deployment:
    working_directory: ~/repo
    docker:
      - image: cimg/node:lts
    environment:
      VERCEL_ORG_ID: $VERCEL_ORG_ID
      VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID
    steps:
      - checkout
      - node/install-packages:
      - pkg-manager: yarn
      - run:
        command: yarn build
      - run:
        command: yarn test
workflows:
  preview_deploymen:
    jobs:
      - preview_deployment:
          filters:
            branches:
              ignore: /dev/
