version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  test:
    docker:
      - image: cimg/node:lts
        environment:
          DATA_BASE_URL: DATA_BASE_URL
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn build
      - run:
          command: yarn test
  build:
    docker:
      - image: cimg/node:lts
        environment:
          DATA_BASE_URL: DATA_BASE_URL
        
    steps:
      - checkout

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  test:
    jobs:
      - test
  build:
    jobs:
      - build
